version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn tsc
      - yarn build:prod
      - cd public
      - aws s3 sync . s3://${S3_BUCKET} --exclude "*.js.map" --delete
    finally:
      - echo Build completed on `date`
