version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 13.13
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build:prod
      - cd build
      - aws s3 sync . s3://${S3_BUCKET} --exclude "*.js.map" --delete
    finally:
      - echo Build completed on `date`
